### ISSUE TITLE
Plugin crashes october

### ISSUE THREAD

**Issue by drussell-lacma** [DallasMuseumArt/FriendsRecommendations#1]
I followed the instructions up to and including "composer install". When I try and use any of the web pages, it crashes.

![untitled](https://cloud.githubusercontent.com/assets/11051047/6278863/70fe5020-b84f-11e4-8443-9f69455a4a13.jpg)

I tried:
# php plugins/dma/recommendations/classes/items/ItemBase.php

and it parsed fine. I have the DMA.friends plugin installed and it seems to be working correctly.

**Comment by carlos-arroyo** [comment]
Could you please post what versions of PHP, Elasticsearch you have installed in your system?

Based on the screen shoot It looks like your have a version of PHP lower that 5.5 since the ''finally' block is available in PHP 5.5 and above.

**Comment by drussell-lacma** [comment]
That would probably be it then. On the github page it shows php 5.4 as 
the requirement. We're at 5.4.37.

Wouldn't it be better to "code around" using the finally statement so 
that you're compatible with earlier
versions of php?

Thanks,
Doug

On 2/19/2015 6:31 PM, Carlos Arroyo wrote:

> Could you please post what versions of PHP, Elasticsearch you have 
> installed in your system?
> 
> Based on the screen shoot It looks like your have a version of PHP 
> lower that 5.5 since the ''finally' block is available in PHP 5.5 and 
> above.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/DallasMuseumArt/FriendsRecommendations/issues/1#issuecomment-75180090.

## 

Douglas Russell
Director of Software Development and Application Support
Los Angeles County Museum of Art
www.lacma.org http://www.lacma.org
T 323.857.4747
E drussell@lacma.org mailto:drussell@lacma.org

**Comment by carlos-arroyo** [comment]
Hi Doug,

The problem here is that Laravel was rising a series of unhandled exceptions when the field was a large datasets. At the end I did find a solution so I am going to check if is safe now to remove the finally block.

I will keep you posted. 
Carlos

**Comment by carlos-arroyo** [comment]
Hi Doug,
I have removed the unnecessary finally block in the commit 448a3a0174e1ae3a10d8edb2c62a3ecdb4e6074c.

Now the plugin should be compatible with PHP 5.4.

Carlos

**Comment by drussell-lacma** [comment]
Hi carlos, now I'm getting a "Class 'Postman' not found" when I click on 
"Friends Settings" in the
admin panel. See attached image.

Thanks,
Doug

**Comment by carlos-arroyo** [comment]
Hi Doug,

I can't  see the attachment you are referring to but Postman is the notification system of Friends plugin. 
So maybe it is an issue in Friends plugin rather that the recommendation engine. But before opening  a new issue I would like to assess that the Recommendation engine is not causing this issue.

Could you please do the following:
- Disable the recommendation plugin in the admin ( http://<your domain>/backend/system/updates/manage )
- Click again in "Friends Settings". If the error still happening is because the issue is in Friends plugin.
  If that is the case could you please open an issue in OctoberFriends with the following info:
  - Screen shoot of the exception you are getting.
  - Copy of the system.log after the exception is throw. ( the october system log should be in the folder <octobercms folder>/app/storage/logs/system.log )

Carlos
